sudo: false
language: node_js
node_js:
  - '8'
  - '9'
cache:
  directories:
    - "$HOME/google-cloud-sdk/"
script:
  - gcloud version || true
  - if [ ! -d "$HOME/google-cloud-sdk/bin" ]; then rm -rf $HOME/google-cloud-sdk; export CLOUDSDK_CORE_DISABLE_PROMPTS=1; curl https://sdk.cloud.google.com | bash; fi
  # Add gcloud to $PATH
  - source /home/travis/google-cloud-sdk/path.bash.inc
  - gcloud version
  - gcloud components install cloud-datastore-emulator
  - gcloud beta emulators datastore start
  - gcloud beta emulators datastore env-init
  - echo DATASTORE_EMULATOR_HOST
install:
  - npm i npminstall && npminstall
after_script:
  - npm test
